name: workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Exécution des tests
      run: echo "Tests passés avec succès"

    - name: Déploiement sur GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
